### PR TITLE
remove redundant SW install with Next.js guide

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
Fixed in https://app.clickup.com/t/4205457/APPOPS-13285

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
@tristanlee85 What's the question here?

**Comment by tristanlee85** [comment]
> @tristanlee85 What's the question here?

IIRC this used to be necessary to register the SW. Is this no longer the case?

**Comment by rishi-raj-jain** [comment]
> > @tristanlee85 What's the question here?
> 
> IIRC this used to be necessary to register the SW. Is this no longer the case?

Our Next connector already builds, injects and register the service worker by default. I'll get a demo spinned up.

**Comment by rishi-raj-jain** [comment]
@tristanlee85 For more context, install was added to the docs to mitigate the interim problem of not being able to DeepFetch. Once resolved in https://app.clickup.com/t/4205457/APPOPS-13285, everything works as expected without user's need to configure anything.

**Comment by rishi-raj-jain** [comment]
@tristanlee85 here's a demo: https://github.com/rishi-raj-jain/edgio-next-sw-demo

**Pull request merged**
