### PR TITLE
Edgio v7 Guides

### PR DESCRIPTION
**Pull request by jsernaque**

### CODE REVIEW

**Comment by jsernaque** [comment]
Preview docs; Do not merge.

**Comment by tristanlee85** [comment]
https://next-auth.js.org/providers/github

Take a look at how these callouts are styled. Also, I see a number of new icon pngs in this PR for the callouts. Any reason not to use MUI/font icons? Easier to embed and style.

**Comment by jsernaque** [comment]
> https://next-auth.js.org/providers/github
> 
> Take a look at how these callouts are styled. Also, I see a number of new icon pngs in this PR for the callouts. Any reason not to use MUI/font icons? Easier to embed and style.

Our security documentation requires support for tips and important notes. Our current implementation does not have symbols for those types of callouts. The most expedient solution was to replace our callout symbols with existing images. However, as I mentioned before, I'm open to using different icons including MUI / font icons.

**Comment by tristanlee85** [comment]
> > https://next-auth.js.org/providers/github
> > Take a look at how these callouts are styled. Also, I see a number of new icon pngs in this PR for the callouts. Any reason not to use MUI/font icons? Easier to embed and style.
> 
> Our security documentation requires support for tips and important notes. Our current implementation does not have symbols for those types of callouts. The most expedient solution was to replace our callout symbols with existing images. However, as I mentioned before, I'm open to using different icons including MUI / font icons.

Makes sense about the new icons 👍 I would work with @adebiyi-adedotun to bring in icons to match your requirements for the security docs. I think with an icon lib they will look 💎 .

**Comment by jsernaque** [comment]
https://edgio-community-docs-app-security.alt.layer0-docs.layer0-perma.link

**Review by tristanlee85 — APPROVED** [review]

**Pull request merged**
